name: Attest artifact

on:
  workflow_call:
    inputs:
      subject-name:
        required: true
        type: string
      subject-digest:
        required: true
        type: string

permissions:
  id-token: write
  attestations: write
  artifact-metadata: write

jobs:
  attest:
    runs-on: ubuntu-latest

    steps:
      - name: Generate artifact attestation
        uses: actions/attest@v4.1.0
        with:
          subject-name: ${{ inputs.subject-name }}
          subject-digest: ${{ inputs.subject-digest }}
